### ISSUE TITLE
在Nginx、MySQL、PHP下安装出现问题

### ISSUE THREAD

**Issue by EAimTY** [yujiandong/simpleforum#1]
在Nginx、MySQL、PHP下安装出现问题
在CentOS和Debian下分别测试了用yum安装和[LNMP一键包](http://lnmp.org)安装，试过PHP5.6与PHP7，在首页界面显示：
![首页](https://cloud.githubusercontent.com/assets/13065214/12702824/2577322c-c86e-11e5-8e22-f012d62ab500.png)
安装php-imagick前，install界面虽不能加载css，但仍可显示安装条件：
![条件](https://cloud.githubusercontent.com/assets/13065214/12702887/b8209e64-c86f-11e5-8a1e-0b83fbc1a55a.jpg)
先前已将所有目录及文件的权限设为777，但仍提示web/avatar没有写权限。在安装php-imagick、修改expose_php=Off后，http://domain.com/install 显示：
![install](https://cloud.githubusercontent.com/assets/13065214/12702866/586238de-c86f-11e5-9dd4-41d5c933c012.png)
查看Chrome开发工具发现，无法get到http://domain.com/static 与 http://domain.com/assets 下的css与js文件。
Nginx版本为1.8.1，配置文件内容与 http://simpleforum.org/t/49 的完全一样。
求解决。。

**Comment by yujiandong** [comment]
你好，能将runtime/logs/app.log文件发送给我吗？里面有出错log。 admin#simpleforum.org

**Comment by EAimTY** [comment]
好的，已发送邮件至admin@simpleforum.org，谢谢

**Comment by yujiandong** [comment]
你好，估计是你的nginx设置问题。
根据log
'SCRIPT_FILENAME' => '/home/forum//index.php'
index.php被指向了'/home/forum//index.php'
正确应该是指向 '/home/forum/web/index.php'

请检查nginx设置中的root设置是否为以下：

root        /home/forum/web;  #web目录路径

**Comment by EAimTY** [comment]
我找到了问题：Nginx的domain.conf中root设置成了/home/forum;没有设置为/home/forum/web;
是我眼花了...没有看到，抱歉打扰到了您，谢谢！

**Comment by EAimTY** [comment]
还有一个问题，就是单独安装过php-gd时install界面的环境检测可以显示，但同时安装php-gd和php-pecl-imagick后，install界面会报错“服务器内部错误”。是不是我配置的问题？还是GD扩展与ImageMagick扩展本身就冲突？

**Comment by yujiandong** [comment]
你好，安装imagick后出错，是个bug，不是冲突。
install_update/controllers/InstallController.php
65行
$imagick = new Imagick();
修改为
$imagick = new \Imagick();
就可以了。
github中的代码已修改。

此外，gd和imagick只要装一个就可以了，不需要两个都安装的

**Comment by EAimTY** [comment]
好的，谢谢
