### ISSUE TITLE
为何不把入口文件放到web子目录中

### ISSUE THREAD

**Issue by gouchaoer** [yujiandong/simpleforum#3]
新的php框架的单入口好处之一就是安全，我看到入口文件在根目录下，那么core目录下的源码都暴露出来了……我的想法是在一个web子目录中放index.php的入口文件，然后upload也放在web子目录中

**Comment by yujiandong** [comment]
现在的结构设计是为了不熟悉的人方便虚拟主机部署。在core/.htaccess或者nginx的配置中屏蔽了core下对php文件的直接访问。

对于熟悉的人来说，完全可以把core目录放到任何地方，然后修改index.php中的SF_PATH设置，这样就不会暴露core中的源代码了。
